from enum import Enum


class ErrorCode(Enum):
    """
    THIS PART CONTAINS GENERAL ERROR CODES
    """

    OBJECT_NOT_FOUND = 10001
    NOT_UPDATED = 10002
    NOT_DELETED = 10003
    NOT_INSERTED = 10004
    UNEXPECTED_DATA = 10005
    """
        THIS PART CONTAINS ERROR CODE FOR AUTH SERVICE
    """
    INCORRECT_USERNAME_OR_PASSWORD = 10006
    USER_NOT_FOUND = 10007
    WALLET_ADDRESS_IS_NOT_VALID = 10008
    TOO_SOON_TO_RESET = 10009
    RESET_REQUEST_NOT_FOUND = 10010
    """
        THIS PART CONTAINS ERROR CODE FOR NOTIFICATION SERVICE
    """
    MISSING_USER_PREF_FOR_NOTIFICATION = 10011
    EMAIL_SERVICE_DOWN = 10012
    """
        THIS PART CONTAINS ERROR CODE FOR OTP
    """
    WRONG_OTP_CODE = 10013
    EMAIL_SENT_ERROR = 10014
    INVALID_OTP_OR_EXPIRED = 10015
